import { blankReturn } from "./blank.ts";
import type { BookReturn } from "./types.ts";

export const SEED_RETURNS: BookReturn[] = [
  blankReturn({
    id: "ret_ledger",
    createdAt: "2026-08-12T14:00:00.000Z",
    updatedAt: "2026-09-14T18:22:00.000Z",
    currentStepId: "meta.isbn",
    status: "needs_info",
    visitedSteps: [
      "house.welcome",
      "house.imprint",
      "house.operator",
      "title.working",
      "title.author",
      "title.language",
      "class.type",
      "class.fiction",
      "class.genre",
      "class.audience",
      "class.heat",
      "rights.origin",
      "rights.territory",
      "rights.exclusive",
      "rights.contract",
      "ms.status",
      "ms.logline",
      "ms.synopsis",
      "ms.counts",
      "ms.outline",
      "edit.passes",
      "edit.quality",
      "edit.legal",
      "meta.title",
      "meta.blurb",
      "meta.keywords",
      "meta.bio",
      "design.trim",
      "design.cover",
      "design.files",
      "audio.decide",
      "budget.cap",
      "budget.lines",
      "dist.channels",
      "dist.pricing",
      "market.launch",
    ],
    imprint: "mangu_romance",
    operator: "House Operator",
    workingTitle: "The Midnight Ledger",
    finalTitle: "The Midnight Ledger",
    subtitle: "A novel of accounts and after-hours",
    seriesName: "The Parsippany Papers",
    seriesNumber: 1,
    hasSeries: true,
    authorName: "A. R. Shah",
    authorPenName: "A. R. Shah",
    language: "en",
    contentType: "novel",
    fiction: true,
    primaryGenre: "contemp_romance",
    subgenres: ["romantic_suspense"],
    bisac: ["FIC027020", "FIC027110"],
    lcgft: ["Romance fiction", "Romantic suspense fiction"],
    audience: "adult",
    heatLevel: "steamy",
    origin: "original",
    territories: ["world"],
    exclusiveKdp: false,
    contractSigned: true,
    royaltyAuthorPct: 50,
    copyrightHolder: "MANGU Publishers",
    logline:
      "A forensic accountant and the night-shift auditor who cooked her books must close the year without closing their hearts.",
    synopsis:
      "Mira Kline is hired to unwind a boutique publisher’s books before a December audit. The numbers only balance after midnight, when Rahul Mehta — the quiet auditor who has kept the house afloat since a hut in Mumbai became an American imprint — walks her through every ledger. As they reconstruct sixty years of royalty statements, they uncover a missing catalog, a grandfather’s unpublished novel, and a heat neither of them budgeted for. Filing day is December 31. So is the wedding she already said yes to.",
    wordCount: 82400,
    chapterCount: 28,
    outline:
      "Act I: The engagement party and the first variance.\nAct II: The hut, the missing ISBN block, the night the press flooded.\nAct III: The December filing, the grandfather’s manuscript, the choice.",
    manuscriptStatus: "revised",
    editorial: {
      developmental: "passed",
      line: "passed",
      copy: "in_progress",
      proof: "not_started",
    },
    sensitivityRead: true,
    legalReview: false,
    qualityBar: "needs_work",
    qualityNotes: "Copyedit in flight. Legal still needs the grandfather-manuscript rights note.",
    isbnPrint: "",
    isbnEbook: "",
    keywords: [
      "workplace romance",
      "accountant hero",
      "family business",
      "second chance",
      "holiday deadline",
      "Indian American",
      "publishing house",
    ],
    description:
      "She was hired to close the books. He had already cooked them — with love, and a sixty-year-old secret.\n\nForensic accountant Mira Kline has six weeks to make a family press look solvent. Night-shift auditor Rahul Mehta knows every number except the one that would let him keep her. A steamy, sharp contemporary romance about ledgers, lineage, and the last filing of the year.",
    authorBio:
      "A. R. Shah writes love stories about work. This is the first novel in The Parsippany Papers.",
    trimSize: "trade",
    interiorColor: "bw",
    paperType: "cream",
    coverStatus: "draft",
    coverBrief:
      "Night office, a single desk lamp, an open leather ledger, two coffee cups. No couple on the cover. Serif title. Ink and cream.",
    epubReady: false,
    printPdfReady: false,
    produceAudio: true,
    narrator: "TBD — dual POV, two voices",
    audioHours: 9.2,
    audioMastered: false,
    budgetCap: 100,
    costs: {
      editorial: 40,
      cover: 25,
      isbn: 10,
      interior: 15,
      audio: 0,
      marketing: 10,
      other: 0,
    },
    channels: {
      kdp: true,
      ingram: true,
      apple: true,
      google: false,
      kobo: false,
      manguStore: true,
      libraries: true,
    },
    listPriceEbook: 4.99,
    listPricePrint: 16.99,
    listPriceAudio: 12.99,
    launchDate: "2026-12-01",
    arcProgram: true,
    goodreads: true,
    marketingNotes: "Romance newsletter blast week of 11/17. House anniversary tie-in.",
  }),
  blankReturn({
    id: "ret_nadi",
    createdAt: "2026-09-01T09:00:00.000Z",
    updatedAt: "2026-09-10T11:40:00.000Z",
    currentStepId: "ms.synopsis",
    status: "in_progress",
    visitedSteps: [
      "house.welcome",
      "house.imprint",
      "house.operator",
      "title.working",
      "title.author",
      "title.language",
      "title.translation",
      "class.type",
      "class.fiction",
      "class.genre",
      "class.audience",
      "rights.origin",
    ],
    imprint: "mangu_world",
    workingTitle: "नदी का घर",
    finalTitle: "",
    subtitle: "",
    authorName: "Kavita Deshmukh",
    language: "hi",
    isTranslation: false,
    sourceLanguage: "",
    sourceTitle: "",
    contentType: "novel",
    fiction: true,
    primaryGenre: "literary",
    subgenres: [],
    audience: "adult",
    heatLevel: "none",
    origin: "original",
    logline: "A widow returns to the house her father built on a drying river and must decide what to carry across.",
    synopsis: "",
    wordCount: 61000,
    chapterCount: 19,
    manuscriptStatus: "draft",
    produceAudio: false,
    budgetCap: 100,
    costs: {
      editorial: 20,
      cover: 0,
      isbn: 0,
      interior: 0,
      audio: 0,
      marketing: 0,
      other: 0,
    },
    listPriceEbook: 3.99,
    listPricePrint: 13.99,
  }),
  blankReturn({
    id: "ret_bela",
    createdAt: "2026-07-22T16:10:00.000Z",
    updatedAt: "2026-09-08T08:05:00.000Z",
    currentStepId: "review.issues",
    status: "ready_to_file",
    visitedSteps: [
      "house.welcome",
      "house.imprint",
      "house.operator",
      "title.working",
      "title.author",
      "title.language",
      "class.type",
      "class.fiction",
      "class.genre",
      "class.audience",
      "class.age",
      "rights.origin",
      "rights.territory",
      "rights.exclusive",
      "rights.contract",
      "ms.status",
      "ms.logline",
      "ms.synopsis",
      "ms.counts",
      "edit.passes",
      "edit.quality",
      "edit.legal",
      "meta.title",
      "meta.blurb",
      "meta.keywords",
      "meta.bio",
      "meta.isbn",
      "design.trim",
      "design.cover",
      "design.files",
      "audio.decide",
      "budget.cap",
      "budget.lines",
      "dist.channels",
      "dist.pricing",
      "market.launch",
      "market.arc",
      "review.issues",
    ],
    imprint: "mangu_children",
    workingTitle: "A Button for Bela",
    finalTitle: "A Button for Bela",
    authorName: "N. Iyer",
    language: "en",
    contentType: "childrens",
    fiction: true,
    primaryGenre: "picture",
    audience: "children",
    ageRange: "3–6",
    heatLevel: "none",
    origin: "original",
    contractSigned: true,
    exclusiveKdp: false,
    logline: "Bela loses the button that holds her red coat closed, and the whole street helps her find a new one.",
    synopsis:
      "On the first cold morning, Bela’s red coat will not close. The button is gone. The tailor, the grocer, the bus driver, and a very small dog each offer a button that is almost right. None of them is hers — until she learns that a coat can hold more than one.",
    wordCount: 420,
    chapterCount: 1,
    manuscriptStatus: "final",
    editorial: {
      developmental: "passed",
      line: "skipped",
      copy: "passed",
      proof: "passed",
    },
    sensitivityRead: true,
    legalReview: true,
    qualityBar: "pass",
    isbnPrint: "978-1-948200-01-1",
    isbnEbook: "978-1-948200-02-8",
    keywords: ["kindness", "community", "coat", "lost and found", "picture book", "Indian American", "winter"],
    description:
      "Bela’s red coat is missing a button. The whole street has one to spare. A warm picture book about neighbors, almost-right answers, and the coat that can hold more than one.",
    authorBio: "N. Iyer writes for the children who count the buttons on the way to school.",
    trimSize: "square",
    interiorColor: "color",
    paperType: "white",
    coverStatus: "final",
    coverBrief: "Red coat, one empty thread, cream ground, Bela in profile. No photos of children.",
    epubReady: true,
    printPdfReady: true,
    produceAudio: false,
    budgetCap: 100,
    costs: {
      editorial: 20,
      cover: 35,
      isbn: 10,
      interior: 25,
      audio: 0,
      marketing: 8,
      other: 0,
    },
    channels: {
      kdp: true,
      ingram: true,
      apple: true,
      google: true,
      kobo: false,
      manguStore: true,
      libraries: true,
    },
    listPriceEbook: 2.99,
    listPricePrint: 12.99,
    launchDate: "2026-10-20",
    arcProgram: true,
    goodreads: true,
    preorder: true,
    digitalOnly: false,
    hasSeries: false,
    interiorTemplate: "square_picture",
    drm: false,
  }),
  blankReturn({
    id: "ret_feather",
    createdAt: "2026-09-05T12:00:00.000Z",
    updatedAt: "2026-09-13T19:00:00.000Z",
    currentStepId: "design.cover",
    status: "in_progress",
    visitedSteps: [
      "house.welcome",
      "house.imprint",
      "title.working",
      "title.author",
      "title.language",
      "class.type",
      "class.fiction",
      "class.genre",
      "class.audience",
      "rights.origin",
      "ms.status",
      "ms.logline",
      "ms.counts",
    ],
    imprint: "mangu_comics",
    workingTitle: "Iron Feather",
    finalTitle: "Iron Feather",
    authorName: "J. Park",
    language: "en",
    contentType: "comics",
    fiction: true,
    primaryGenre: "graphic_novel",
    audience: "ya",
    heatLevel: "none",
    origin: "original",
    logline: "A courier with a metal wing runs black-market letters across a partitioned city.",
    wordCount: 12000,
    chapterCount: 6,
    manuscriptStatus: "outline",
    produceAudio: false,
    interiorColor: "color",
    trimSize: "digest",
    coverStatus: "briefed",
    coverBrief: "Split city, one iron primary feather catching streetlight. Limited palette: ink, rust, cream.",
    interiorTemplate: "digest_comics",
    hasSeries: false,
    budgetCap: 100,
    costs: {
      editorial: 10,
      cover: 20,
      isbn: 0,
      interior: 40,
      audio: 0,
      marketing: 0,
      other: 0,
    },
    listPriceEbook: 6.99,
    listPricePrint: 18.99,
  }),
];
